### ISSUE TITLE
needs updating

### ISSUE THREAD

**Issue by girlsintheoffice** [miguel-perez/OkCupidHack#4]
Newbie here, so apologies if I'm not going about submitting this issue correctly, but the OkCupidHack no longer works since okc has updated their Boost feature earlier this year. I'm not entirely sure how to go about updating it, so I thought I'd see if anyone else here would be willing to help out a bit? thanks!

**Comment by iengineer** [comment]
I'll take a look when I free up some time.

**Comment by girlsintheoffice** [comment]
Really? THANK YOU! My love life has seriously tanked since the script
stopped working. I've tried to fix it, but I'm not so great at javascript
just yet. Please keep me updated!

On Sat, Mar 12, 2016 at 4:36 PM, Wadson Fleurigene <notifications@github.com
